# Generated by Django 3.0.6 on 2020-08-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
