# Generated by Django 3.0.6 on 2020-09-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimodel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
