# Generated by Django 3.0.6 on 2020-09-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200922_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimodel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
